[package]
name = "spotifyarch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0"
anyhow = "1.0"
rpassword = "3.0.1"
